"use client"

import { useEffect, useState } from "react"
import { createClientComponentClient } from "@supabase/auth-helpers-nextjs"
import { User, Mail, Phone, MapPin } from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Skeleton } from "@/components/ui/skeleton"
import { toast } from "@/components/ui/use-toast"
import type { Database } from "@/lib/database.types"

// Corrected type definition for Profiles
type Profiles = Database["public"]["Tables"]["user_profiles"]["Row"]

export default function DashboardProfilePage() {
  const [userProfile, setUserProfile] = useState<Profiles | null>(null)
  const [loading, setLoading] = useState(true)
  const supabase = createClientComponentClient<Database>()

  useEffect(() => {
    const fetchUserProfile = async () => {
      setLoading(true)
      try {
        const {
          data: { session },
          error: sessionError,
        } = await supabase.auth.getSession()

        if (sessionError) throw sessionError
        if (!session) {
          toast({
            title: "Authentication Required",
            description: "Please log in to view your profile.",
            variant: "destructive",
          })
          return
        }

        // Fetch profile using user_id which links to auth.users.id
        const { data: profileData, error: profileError } = await supabase
          .from("user_profiles")
          .select("*")
          .eq("user_id", session.user.id) // Use user_id here
          .single()

        if (profileError && profileError.code !== "PGRST116") {
          // PGRST116 means no rows found
          throw profileError
        }

        if (profileData) {
          setUserProfile(profileData)
        } else {
          // Fallback if no profile found, use basic user info from auth.users
          // and set user_id for consistency. 'id' will be generated by DB on insert.
          setUserProfile({
            id: 0, // Placeholder for number type, will be ignored on insert
            user_id: session.user.id,
            email: session.user.email || "N/A",
            full_name: session.user.user_metadata?.full_name || null,
            phone_number: session.user.phone || null,
            address: null,
            created_at: new Date().toISOString(), // Use current date for fallback
          })
          toast({
            title: "Profile Not Found",
            description: "Your detailed profile could not be loaded. Please update it in settings.",
            variant: "default",
          })
        }
      } catch (error) {
        console.error("Error fetching user profile:", error)
        toast({
          title: "Error",
          description: "Failed to load profile details.",
          variant: "destructive",
        })
      } finally {
        setLoading(false)
      }
    }

    fetchUserProfile()
  }, [supabase])

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-10 w-64" />
        <Card>
          <CardHeader>
            <Skeleton className="h-6 w-48 mb-2" />
            <Skeleton className="h-4 w-72" />
          </CardHeader>
          <CardContent className="space-y-4">
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-10 w-32" />
          </CardContent>
        </Card>
      </div>
    )
  }

  if (!userProfile) {
    return (
      <div className="text-center py-12">
        <h2 className="text-2xl font-bold mb-2">Profile Not Available</h2>
        <p className="text-gray-500 mb-6">Could not load your profile information.</p>
        <Button asChild>
          <Link href="/dashboard/settings">Go to Settings</Link>
        </Button>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold tracking-tight">My Profile</h1>

      <Card>
        <CardHeader>
          <CardTitle>Personal Information</CardTitle>
          <CardDescription>Manage your profile details.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center space-x-3">
            <User className="h-5 w-5 text-muted-foreground" />
            <p className="text-sm font-medium">Name: {userProfile.full_name || "Not set"}</p>
          </div>
          <div className="flex items-center space-x-3">
            <Mail className="h-5 w-5 text-muted-foreground" />
            <p className="text-sm font-medium">Email: {userProfile.email}</p>
          </div>
          <div className="flex items-center space-x-3">
            <Phone className="h-5 w-5 text-muted-foreground" />
            <p className="text-sm font-medium">Phone: {userProfile.phone_number || "Not set"}</p>
          </div>
          <div className="flex items-center space-x-3">
            <MapPin className="h-5 w-5 text-muted-foreground" />
            <p className="text-sm font-medium">Address: {userProfile.address || "Not set"}</p>
          </div>
          <Button asChild>
            <Link href="/dashboard/settings">Edit Profile</Link>
          </Button>
        </CardContent>
      </Card>
    </div>
  )
}
